config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  root to: "foods#index"
  
  resources :users
  resources :recipes, only: %i[index new create show destroy]
  resources :recipes, only: [:index, :new, :create, :show, :destroy] do
    resources :recipe_foods, only: [:new, :create]
  end
  resources :foods, only: [:index, :new, :create, :destroy]
  
  get '/public_recipes', to: 'recipes#public_recipes'
  get '/general_shopping_list', to: 'foods#general_shopping_list'
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
    can :add_new_food, Recipe do |recipe|
      recipe.user == user
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, dependent: :delete_all
  belongs_to :user
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, dependent: :delete_all
  belongs_to :user
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods
  has_many :recipes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :authenticate_user!

  def index
    @user = current_user
    @user_foods = @user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(form_params.merge(user: current_user))

    if @food.save
      redirect_to foods_url
    else
      render :new
    end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    redirect_to foods_url
  end

  def general_shopping_list
    @missing_foods = []
    current_user.recipes.each do |recipe|
      recipe.recipe_foods.each do |recipe_food|
        @food = recipe_food.food
        @missing_foods << recipe_food unless current_user.foods.include?(@food)
      end
    end
    @total_price = 0
    @missing_foods.each do |missing_food|
      @food = missing_food.food
      @total_price += @food.price * missing_food.quantity
    end
  end

  private

  def form_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def index; end

  def new
    @foods = Food.where(user_id: current_user.id)
    @recipe_food = RecipeFood.new
  end

  def create
    unless current_user
      redirect_to new_user_registration_url, notice: 'Please, signup to create a recipe'
      return
    end

    data = params.require(:recipe_food).permit(:quantity, :food)
    recipe_food = RecipeFood.new(quantity: data[:quantity], recipe_id: params[:recipe_id], food_id: data[:food])
    recipe_food.recipe_id = params[:recipe_id]
    if recipe_food.save
      redirect_to recipe_url(params[:recipe_id])
    else
      render :new, locals: { recipe_food: }
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!, except: [:public_recipe]

  def index
    @user = current_user
    @user_recipes = @user.recipes
  end

  def new
    @recipe = Recipe.new
  end

  def create
    unless current_user
      redirect_to new_user_registration_url, notice: 'Please, signup to create a recipe'
      return
    end

    recipe = Recipe.new(recipe_params)
    recipe.user = current_user
    if recipe.save
      redirect_to recipes_url
    else
      render :new, locals: { recipe: }
    end
  end

  def show
    @recipe = Recipe.find_by(id: params[:id])
    @foods = @recipe.recipe_foods.map(&:food)
  end

  def destroy
    recipe = Recipe.find(params[:id])
    recipe.destroy
    redirect_to recipes_url, notice: 'Recipe deleted successfully'
  end

  def public_recipes
    @public_recipes = Recipe.where(public: true).order(created_at: :desc)
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/foods/general_shopping_list.html.erb
<%= render partial: 'partials/navigation_menu', locals: {visited: 'shopping_list'} %>
<h1>Shopping List</h1>
<div class='shopping-list-header'>
  <h3>Amout of items to buy: <%= @missing_foods.count %></h3>
  <h3>Total value of food needed: $<%= @total_price %></h3>
</div>
<div>
  <div class='food-header'>
    <h3 class='food-name'>Food</h3>
    <h3 class='food-quantity'>Quantity</h3>
    <h3 class='delete-food'>Price</h3>
  </div>
  <ul class='food-list'>
    <% @missing_foods.each do |food| %>
      <li class='food-item'>
        <h3 class='food-name'><%= food.food.name %></h3>
        <h3 class='food-quantity'><%= food.quantity %> <%= food.food.measurement_unit %></h3>
        <h3 class='food-price'>$<%= food.food.price * food.quantity %></h3>
      </li>
    <% end %>
  </ul>
</div>

app/views/foods/index.html.erb
<%= render partial: 'partials/navigation_menu', locals: {visited: 'foods'} %>
<div class='food-container'>
  <div class='add-new-food-button'><%= link_to "Add food", new_food_path, class: "add-new-food-button" %></div>
  <div class='food-header'>
    <h3 class='food-name'>Food</h3>
    <h3 class='food-measurement_unit'>Measurement unit</h3>
    <h3 class='food-price'>Unit price</h3>
    <h3 class='food-quantity'>Quantity</h3>
    <h3 class='delete-food'>Actions</h3>
  </div>
  <ul class='food-list'>
    <% @user_foods.each do |food| %>
      <li class='food-item'>
        <h3 class='food-name'><%= food.name %></h3>
        <h3 class='food-measurement_unit'><%= food.measurement_unit %></h3>
        <h3 class='food-price'>$<%= food.price %></h3>
        <h3 class='food-quantity'><%= food.quantity %> <%= food.measurement_unit %></h3>
        <div class='delete-food'><%= button_to 'Delete', food_url(food), method: :delete %></div>
      </li>
    <% end %>
  </ul>
</div>

app/views/foods/new.html.erb
<h1>Add new food</h1>
<%= form_with model: @food, url: foods_path do |f| %>
  <div>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :measurement_unit %><br>
    <%= f.text_field :measurement_unit %>
  </div>
  <div>
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div>
    <%= f.label :quantity %><br>
    <%= f.text_field :quantity %>
  </div>
  <%= f.submit "Create Food" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/partials/_navigation_menu.html.erb
<div class='header'>

  <%= link_to "Foods", "/foods", class: "#{visited == 'foods' ? 'foods_page' : ''}" %>
  <%= link_to "Recipes", "/recipes", class: "#{visited == 'recipes' ? 'recipes_page' : ''}" %>
  <%= link_to "Public Recipes", "/public_recipes", class: "#{visited == 'public_recipes' ? 'public_recipes' : ''}" %>
  <%= link_to "Shopping List", "/general_shopping_list", class: "#{visited == 'shopping_list' ? 'shopping_list' : ''}" %>

  <% if(current_user) %>
    <%= button_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= button_to 'Sign In', user_session_path, method: :post %>
  <% end %>
</div>

app/views/recipe_foods/_form.html.erb
<%= form_with model: @recipe_food, url: recipe_recipe_foods_path(params[:recipe_id]), method: :post, local: true do |form| %>

  <%= form.number_field :quantity, placeholder: "Enter quantity", :required => true %>

  <div class="label-container">
    <%= form.label :food, class: "label" %>
    <% options = @foods.map do |food| %>
      <% [food[:name], food[:id]] %>
    <% end %>
    <%= form.select :food, options_for_select(options), :required => true %>
  </div>

  <%= form.submit class: "submit-button" %>
<% end %>

app/views/recipe_foods/new.html.erb
<section class="section-full-page">
  <div class="recipe form-container">
    <h1>Add Ingredient</h1>
    <%= render "form" %>
    <%= link_to recipe_path(params[:recipe_id]) do%>
      <button class="back-to-recipes">Back to Recipe</button>
    <% end %>
  </div>
</section>

  

app/views/recipes/_form.html.erb
<%= form_with model: @recipe, url: recipes_path, method: :post, local: true do |form| %>

  <%= form.text_field :name, placeholder: "Enter name of recipe...", :required => true %>

  <%= form.number_field :preparation_time, placeholder: "Enter preparation time", :required => true %>

  <%= form.number_field :cooking_time, placeholder: "Enter cooking time...", :required => true %>

  <div class="label-container">
    <%= form.label :public, class: "label" %>
    <%= form.select :public, options_for_select(["True", "False"]), :required => true %>
  </div>

  <%= form.text_area :description, placeholder: "Enter recipe's description...", :required => true %>

  <%= form.submit class: "submit-button" %>
<% end %>
  

app/views/recipes/_recipe_card.html.erb
<div class='recipe dflex-row'>
  <div class="recipe-action dflex-col">
    <%= link_to recipe_path(recipe) do %>
      <h2><%= recipe.name %></h2>
    <% end %> 
    <%= button_to 'Remove', recipe_url(recipe), method: :delete %>
  </div>
  <p class="recipe-desc"><%= recipe.description %></p>
</div>

app/views/recipes/_switch_button.html.erb
<div class="dflex-row show-public">
  <p>Public</p>
  <label class="switch">
    <input type="checkbox"
      <% unless !public %>
        checked
      <% end %>
    disabled=true>
    <span class="slider round"></span>
  </label>
</div>

app/views/recipes/index.html.erb
<%= render partial: 'partials/navigation_menu', locals: {visited: 'recipes'} %>
<section class="section-full-page">
  <div class="recipes-container"> 
    <%= button_to 'New Recipe', new_recipe_url, method: :get, class: 'new-recipe' %>
    <div class="recipes">
      <% if(@user_recipes.any?) %>
        <% @user_recipes.each do |recipe| %>
          <%= render partial: 'recipe_card', locals: {recipe: recipe} %>
        <% end %>
      <% else %>
        <P class="show-message"><%= "No recipe to show" %>
      <% end %>
    </div>
  </div>
</section>

app/views/recipes/new.html.erb
<section class="section-full-page">
  <div class="recipe form-container">
    <h1>New Recipe</h1>
    <%= render "form" %>
    <%= link_to recipes_path do%>
      <button class="back-to-recipes">Back to Recipes</button>
    <% end %>
  </div>
</section>

app/views/recipes/public_recipes.html.erb
<%= render partial: 'partials/navigation_menu', locals: {visited: 'public_recipes'} %>
<h1>Public Recipes</h1>
<ul class='public-recipes-container'>
  <% @public_recipes.each do |recipe| %>
    <%= link_to "/recipes/#{recipe.id}" do %>
      <li class='public-recipe-card'>
        <div>
          <h2><%= recipe.name %></h2>
          <h3>By: <%= recipe.user.name %></h3>
        </div>
        <div>
          <h3>Total food items: <%= recipe.recipe_foods.count %></h3>
          <% @ingredient_ids = recipe.recipe_foods.pluck(:food_id) %>
          <% @total_price = Food.where(id: @ingredient_ids).sum(:price) %>
          <h3>Total price: <%= @total_price %></h3>
        </div>
      </li>
    <% end %>
  <% end %>
</ul>

app/views/recipes/show.html.erb
<%= render partial: 'partials/navigation_menu', locals: {visited: 'recipes'} %>
<main class="show-recipe dflex-col">
  <h2><%= @recipe.name %></h2>
  <div class="dflex-row line1">
    <p><span>Preparation Time:</span> <%= @recipe.preparation_time %>hour</p>
    <%= render partial: 'switch_button', locals: {public: @recipe.public} %>
  </div>
  <div class="dflex-col line2">
    <p><span>Cooking time:</span> <%= @recipe.cooking_time %>hours</p>
    <p><span>Description:</span> <br/> <%= @recipe.description %></p>
  </div>

  <div class="dflex-row line3">
    <%= button_to 'Generate Shopping List', '/general_shopping_list', method: :get %>
    <% if can? :add_new_food, @recipe %>
      <%= button_to 'Add Ingredient', new_recipe_recipe_food_path(@recipe.id), method: :get %>
    <% end %>
  </div>

  <hr/>
  <table class="foods" cellspacing=0>
    <thead>
      <tr>
        <th>Food</th>
        <th>Quantity</th>
        <th>Value</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each do |food| %>
        <tr>
          <td><%= food.name %></td>
          <td><%= food.quantity %> <%= food.measurement_unit %></td>
          <td>$<%= food.price %></td>
          <td><div class='delete-food'><%= button_to 'Delete', food_url(food), method: :delete %></div></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</main>